name: AI Issue Analysis

on:
  issues:
    types: [opened]

jobs:
  analyze-issue:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js for repomix
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Setup Python for AI analysis
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install repomix
        run: |
          npm install -g repomix
          echo "Repomix installed successfully"
          repomix --version
      
      - name: Generate repomix output for ansible-creator
        run: |
          echo "Running repomix on ansible-creator repository using remote..."
          repomix --remote https://github.com/ansible/ansible-creator --output repomix-output.txt
          echo "Repomix output generated successfully"
          ls -la repomix-output.txt
      
      - name: Clone AI-Issue-Triage repository
        uses: actions/checkout@v4
        with:
          repository: shvenkat-rh/AI-Issue-Triage
          ref: updated-genai-package
          path: ai-triage
          fetch-depth: 1
      
      - name: Install Python dependencies for AI triage
        run: |
          cd ai-triage
          pip install -r requirements.txt
          echo "Python dependencies installed successfully"
      
      - name: Prepare issue content
        id: issue-content
        run: |
          # Extract issue title and body safely
          echo "Issue content prepared"

      - name: Check for prompt injection
        id: prompt-injection
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        run: |
          cd ai-triage
          
          echo "Checking for prompt injection..."
          echo "ISSUE_TITLE: '$ISSUE_TITLE'"
          echo "ISSUE_DESCRIPTION: '$ISSUE_DESCRIPTION'"
          
          # Use the prompt injection detection from the AI-Issue-Triage repository
          if [ -f "prompt_injection.py" ]; then
            echo "Using prompt_injection.py for security check"
            
            # Run prompt injection detection using the correct module approach
            python3 -c "
import os
import json
from prompt_injection import detect_prompt_injection

title = os.environ.get('ISSUE_TITLE', '')
description = os.environ.get('ISSUE_DESCRIPTION', '')

print('Testing title for prompt injection...')
title_result = detect_prompt_injection(title) if title else None

print('Testing description for prompt injection...')
desc_result = detect_prompt_injection(description) if description else None

# Determine if either has injection
has_injection = False
risk_level = 'safe'
confidence = 0.0
detected_patterns = []

if title_result and title_result.is_injection:
    has_injection = True
    risk_level = title_result.risk_level.value
    confidence = max(confidence, title_result.confidence_score)
    if title_result.detected_patterns:
        detected_patterns.extend(title_result.detected_patterns)

if desc_result and desc_result.is_injection:
    has_injection = True
    risk_level = desc_result.risk_level.value
    confidence = max(confidence, desc_result.confidence_score)
    if desc_result.detected_patterns:
        detected_patterns.extend(desc_result.detected_patterns)

result = {
    'has_prompt_injection': has_injection,
    'risk_level': risk_level,
    'confidence_score': confidence,
    'detected_patterns': detected_patterns[:3]  # Limit to first 3 patterns
}

print(json.dumps(result, indent=2))
" > prompt_injection_result.json 2>&1
            
            echo "Script execution completed, checking results..."
            echo "Contents of prompt_injection_result.json:"
            cat prompt_injection_result.json || echo "No result file created"
            
            # Parse results
            if [ -f prompt_injection_result.json ]; then
              HAS_INJECTION=$(jq -r '.has_prompt_injection // false' prompt_injection_result.json 2>/dev/null || echo "false")
              RISK_LEVEL=$(jq -r '.risk_level // "safe"' prompt_injection_result.json 2>/dev/null || echo "safe")
              echo "Parsed has_prompt_injection: $HAS_INJECTION"
              echo "Parsed risk_level: $RISK_LEVEL"
              echo "has_prompt_injection=$HAS_INJECTION" >> $GITHUB_OUTPUT
              echo "risk_level=$RISK_LEVEL" >> $GITHUB_OUTPUT
              
              if [ "$HAS_INJECTION" = "true" ]; then
                echo "SECURITY ALERT: Prompt injection detected! Risk Level: $RISK_LEVEL"
              else
                echo "No prompt injection detected"
              fi
            else
              echo "No result file found, assuming no injection"
              echo "has_prompt_injection=false" >> $GITHUB_OUTPUT
              echo "risk_level=safe" >> $GITHUB_OUTPUT
            fi
          else
            echo "prompt_injection.py not found, skipping security check"
            echo "has_prompt_injection=false" >> $GITHUB_OUTPUT
            echo "risk_level=safe" >> $GITHUB_OUTPUT
          fi

      - name: Post prompt injection warning
        if: steps.prompt-injection.outputs.has_prompt_injection == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = 'Prompt injection detected';
            
            // Post the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('Prompt injection warning posted');

      - name: Fetch existing issues for duplicate check
        id: fetch-issues
        if: steps.prompt-injection.outputs.has_prompt_injection != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Get all open issues (excluding the current one)
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            
            // Filter out pull requests and the current issue
            const actualIssues = issues.filter(issue => 
              !issue.pull_request && 
              issue.number !== context.issue.number
            );
            
            // Create issues data file for duplicate_cli
            const issuesData = actualIssues.map(issue => ({
              number: issue.number,
              title: issue.title,
              body: issue.body || '',
              url: issue.html_url
            }));
            
            fs.writeFileSync('existing_issues.json', JSON.stringify(issuesData, null, 2));
            console.log(`Fetched ${actualIssues.length} existing issues for duplicate checking`);

      - name: Check for duplicate issues
        id: duplicate-check
        if: steps.prompt-injection.outputs.has_prompt_injection != 'true'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        run: |
          cd ai-triage
          
          # Copy the repomix output and issues data to the AI triage directory
          cp ../repomix-output.txt .
          cp ../existing_issues.json .
          
          # Run duplicate check first
          echo "Checking for duplicate issues..."
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
          echo "Checking if duplicate_cli.py exists: $(ls -la duplicate_cli.py 2>/dev/null || echo 'NOT FOUND')"
          
          # Check if duplicate_cli.py exists and is executable
          if [ ! -f "duplicate_cli.py" ]; then
            echo "ERROR: duplicate_cli.py not found in ai-triage directory"
            echo "Available Python files:"
            find . -name "*.py" -type f
            exit 1
          fi
          
          # Run duplicate check with error handling
          set +e  # Don't exit on error temporarily
          python duplicate_cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --issues existing_issues.json \
            --output json > duplicate_result.json 2>&1
          
          DUPLICATE_EXIT_CODE=$?
          set -e  # Re-enable exit on error
          
          if [ $DUPLICATE_EXIT_CODE -ne 0 ]; then
            echo "ERROR: duplicate_cli.py failed with exit code $DUPLICATE_EXIT_CODE"
            echo "Output from duplicate_result.json:"
            cat duplicate_result.json 2>/dev/null || echo "No output file created"
            
            # Create a fallback result indicating no duplicate found
            echo '{"is_duplicate": false, "error": "duplicate_cli.py failed"}' > duplicate_result.json
            echo "No duplicate detected (duplicate_cli.py failed)" > duplicate_result.txt
          else
            # Also generate text format for duplicate check
            python duplicate_cli.py \
              --title "$ISSUE_TITLE" \
              --description "$ISSUE_DESCRIPTION" \
              --issues existing_issues.json \
              --output text > duplicate_result.txt
          fi
          
          echo "Duplicate check completed"
          
          # Check if duplicate was found
          if [ -f duplicate_result.json ]; then
            IS_DUPLICATE=$(jq -r '.is_duplicate // false' duplicate_result.json)
            echo "is_duplicate=$IS_DUPLICATE" >> $GITHUB_OUTPUT
            
            if [ "$IS_DUPLICATE" = "true" ]; then
              DUPLICATE_ISSUE_URL=$(jq -r '.duplicate_issue_url // ""' duplicate_result.json)
              DUPLICATE_ISSUE_NUMBER=$(jq -r '.duplicate_issue_number // ""' duplicate_result.json)
              echo "duplicate_issue_url=$DUPLICATE_ISSUE_URL" >> $GITHUB_OUTPUT
              echo "duplicate_issue_number=$DUPLICATE_ISSUE_NUMBER" >> $GITHUB_OUTPUT
              echo "Duplicate issue found: $DUPLICATE_ISSUE_URL"
            fi
          fi

      - name: Run AI issue analysis
        id: analysis
        if: steps.duplicate-check.outputs.is_duplicate != 'true' && steps.prompt-injection.outputs.has_prompt_injection != 'true'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        run: |
          cd ai-triage
          
          # Run the CLI analysis using environment variables
          echo "Running AI analysis..."
          python cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --format json \
            --output analysis_result.json \
            --quiet
          
          echo "Analysis completed successfully"
          
          # Also generate a text format for the comment
          python cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --format text \
            --output analysis_result.txt \
            --quiet
          
          echo "Text analysis generated"
      
      - name: Parse Analysis Results
        id: parse
        if: steps.duplicate-check.outputs.is_duplicate != 'true' && steps.prompt-injection.outputs.has_prompt_injection != 'true'
        run: |
          cd ai-triage
          
          # Extract key information from the analysis
          ISSUE_TYPE=$(jq -r '.issue_type' analysis_result.json)
          SEVERITY=$(jq -r '.severity' analysis_result.json)
          CONFIDENCE=$(jq -r '.confidence_score' analysis_result.json)
          SUMMARY=$(jq -r '.analysis_summary' analysis_result.json)
          
          echo "issue_type=$ISSUE_TYPE" >> $GITHUB_OUTPUT
          echo "severity=$SEVERITY" >> $GITHUB_OUTPUT
          echo "confidence=$CONFIDENCE" >> $GITHUB_OUTPUT
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Post duplicate issue comment
        if: steps.duplicate-check.outputs.is_duplicate == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read the duplicate check result
            let duplicateText;
            try {
              duplicateText = fs.readFileSync('ai-triage/duplicate_result.txt', 'utf8');
            } catch (error) {
              console.error('Error reading duplicate result file:', error);
              duplicateText = 'This issue appears to be a duplicate, but failed to read detailed analysis.';
            }
            
            const duplicateUrl = '${{ steps.duplicate-check.outputs.duplicate_issue_url }}';
            const duplicateNumber = '${{ steps.duplicate-check.outputs.duplicate_issue_number }}';
            
            let comment = '**Duplicate Issue Detected**\n\n';
            comment += duplicateText + '\n\n';
            
            if (duplicateUrl) {
              comment += `**Related Issue**: ${duplicateUrl}\n`;
            } else if (duplicateNumber) {
              comment += `**Related Issue**: #${duplicateNumber}\n`;
            }
            
            comment += '\n---\n*This analysis was performed automatically by AI.*';
            
            // Post the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('Duplicate issue comment posted successfully');

      - name: Post analysis as issue comment
        if: steps.duplicate-check.outputs.is_duplicate != 'true' && steps.prompt-injection.outputs.has_prompt_injection != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read the analysis result
            let analysisText;
            try {
              analysisText = fs.readFileSync('ai-triage/analysis_result.txt', 'utf8');
            } catch (error) {
              console.error('Error reading analysis file:', error);
              analysisText = 'Failed to read analysis results.';
            }
            
            // Use plain text analysis result without formatting
            const comment = analysisText;
            
            // Post the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('Analysis comment posted successfully');
      
      - name: Add Labels Based on Analysis
        uses: actions/github-script@v7
        with:
          script: |
            const isDuplicate = '${{ steps.duplicate-check.outputs.is_duplicate }}' === 'true';
            const issueType = '${{ steps.parse.outputs.issue_type }}';
            const severity = '${{ steps.parse.outputs.severity }}';
            
            const labels = [];
            
            if (isDuplicate) {
              // Add duplicate-specific labels
              labels.push('gemini-analyzed');
              labels.push('duplicate');
            } else {
              // Add analysis label
              labels.push('gemini-analyzed');
              
              // Add type label if available
              if (issueType && issueType !== 'null' && issueType !== '') {
                labels.push(`type:${issueType.toLowerCase()}`);
              }
              
              // Add severity label if available
              if (severity && severity !== 'null' && severity !== '') {
                labels.push(`severity:${severity.toLowerCase()}`);
              }
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
              
              console.log(`Added labels: ${labels.join(', ')}`);
            }
      
      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: issue-analysis-${{ github.event.issue.number }}
          path: |
            existing_issues.json
            ai-triage/duplicate_result.json
            ai-triage/duplicate_result.txt
            ai-triage/analysis_result.json
            ai-triage/analysis_result.txt
            repomix-output.txt
          retention-days: 30

