name: AI Issue Analysis

on:
  issues:
    types: [opened]

jobs:
  analyze-issue:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js for repomix
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Setup Python for AI analysis
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install repomix
        run: |
          npm install -g repomix
          echo "Repomix installed successfully"
          repomix --version
      
      - name: Generate repomix output for ansible-creator
        run: |
          echo "Running repomix on ansible-creator repository using remote..."
          repomix --remote https://github.com/ansible/ansible-creator --output repomix-output.txt
          echo "Repomix output generated successfully"
          ls -la repomix-output.txt
      
      - name: Clone AI-Issue-Triage repository
        uses: actions/checkout@v4
        with:
          repository: shvenkat-rh/AI-Issue-Triage
          ref: updated-genai-package
          path: ai-triage
          fetch-depth: 1
      
      - name: Install Python dependencies for AI triage
        run: |
          cd ai-triage
          pip install -r requirements.txt
          echo "Python dependencies installed successfully"
      
      - name: Prepare issue content
        id: issue-content
        run: |
          # Extract issue title and body safely
          echo "Issue content prepared"
      
      - name: Check for duplicate issues
        id: duplicate-check
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        run: |
          cd ai-triage
          
          # Copy the repomix output to the AI triage directory
          cp ../repomix-output.txt .
          
          # Run duplicate check first
          echo "Checking for duplicate issues..."
          python duplicate_cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --format json \
            --output duplicate_result.json \
            --quiet
          
          # Also generate text format for duplicate check
          python duplicate_cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --format text \
            --output duplicate_result.txt \
            --quiet
          
          echo "Duplicate check completed"
          
          # Check if duplicate was found
          if [ -f duplicate_result.json ]; then
            IS_DUPLICATE=$(jq -r '.is_duplicate // false' duplicate_result.json)
            echo "is_duplicate=$IS_DUPLICATE" >> $GITHUB_OUTPUT
            
            if [ "$IS_DUPLICATE" = "true" ]; then
              DUPLICATE_ISSUE_URL=$(jq -r '.duplicate_issue_url // ""' duplicate_result.json)
              DUPLICATE_ISSUE_NUMBER=$(jq -r '.duplicate_issue_number // ""' duplicate_result.json)
              echo "duplicate_issue_url=$DUPLICATE_ISSUE_URL" >> $GITHUB_OUTPUT
              echo "duplicate_issue_number=$DUPLICATE_ISSUE_NUMBER" >> $GITHUB_OUTPUT
              echo "Duplicate issue found: $DUPLICATE_ISSUE_URL"
            fi
          fi

      - name: Run AI issue analysis
        id: analysis
        if: steps.duplicate-check.outputs.is_duplicate != 'true'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        run: |
          cd ai-triage
          
          # Run the CLI analysis using environment variables
          echo "Running AI analysis..."
          python cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --format json \
            --output analysis_result.json \
            --quiet
          
          echo "Analysis completed successfully"
          
          # Also generate a text format for the comment
          python cli.py \
            --title "$ISSUE_TITLE" \
            --description "$ISSUE_DESCRIPTION" \
            --format text \
            --output analysis_result.txt \
            --quiet
          
          echo "Text analysis generated"
      
      - name: Parse Analysis Results
        id: parse
        if: steps.duplicate-check.outputs.is_duplicate != 'true'
        run: |
          cd ai-triage
          
          # Extract key information from the analysis
          ISSUE_TYPE=$(jq -r '.issue_type' analysis_result.json)
          SEVERITY=$(jq -r '.severity' analysis_result.json)
          CONFIDENCE=$(jq -r '.confidence_score' analysis_result.json)
          SUMMARY=$(jq -r '.analysis_summary' analysis_result.json)
          
          echo "issue_type=$ISSUE_TYPE" >> $GITHUB_OUTPUT
          echo "severity=$SEVERITY" >> $GITHUB_OUTPUT
          echo "confidence=$CONFIDENCE" >> $GITHUB_OUTPUT
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Post duplicate issue comment
        if: steps.duplicate-check.outputs.is_duplicate == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read the duplicate check result
            let duplicateText;
            try {
              duplicateText = fs.readFileSync('ai-triage/duplicate_result.txt', 'utf8');
            } catch (error) {
              console.error('Error reading duplicate result file:', error);
              duplicateText = 'This issue appears to be a duplicate, but failed to read detailed analysis.';
            }
            
            const duplicateUrl = '${{ steps.duplicate-check.outputs.duplicate_issue_url }}';
            const duplicateNumber = '${{ steps.duplicate-check.outputs.duplicate_issue_number }}';
            
            let comment = '**Duplicate Issue Detected**\n\n';
            comment += duplicateText + '\n\n';
            
            if (duplicateUrl) {
              comment += `**Related Issue**: ${duplicateUrl}\n`;
            } else if (duplicateNumber) {
              comment += `**Related Issue**: #${duplicateNumber}\n`;
            }
            
            comment += '\n---\n*This analysis was performed automatically by AI.*';
            
            // Post the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('Duplicate issue comment posted successfully');

      - name: Post analysis as issue comment
        if: steps.duplicate-check.outputs.is_duplicate != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read the analysis result
            let analysisText;
            try {
              analysisText = fs.readFileSync('ai-triage/analysis_result.txt', 'utf8');
            } catch (error) {
              console.error('Error reading analysis file:', error);
              analysisText = 'Failed to read analysis results.';
            }
            
            // Use plain text analysis result without formatting
            const comment = analysisText;
            
            // Post the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('Analysis comment posted successfully');
      
      - name: Add Labels Based on Analysis
        uses: actions/github-script@v7
        with:
          script: |
            const isDuplicate = '${{ steps.duplicate-check.outputs.is_duplicate }}' === 'true';
            const issueType = '${{ steps.parse.outputs.issue_type }}';
            const severity = '${{ steps.parse.outputs.severity }}';
            
            const labels = [];
            
            if (isDuplicate) {
              // Add duplicate-specific labels
              labels.push('gemini-analyzed');
              labels.push('duplicate');
            } else {
              // Add analysis label
              labels.push('gemini-analyzed');
              
              // Add type label if available
              if (issueType && issueType !== 'null' && issueType !== '') {
                labels.push(`type:${issueType.toLowerCase()}`);
              }
              
              // Add severity label if available
              if (severity && severity !== 'null' && severity !== '') {
                labels.push(`severity:${severity.toLowerCase()}`);
              }
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
              
              console.log(`Added labels: ${labels.join(', ')}`);
            }
      
      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: issue-analysis-${{ github.event.issue.number }}
          path: |
            ai-triage/duplicate_result.json
            ai-triage/duplicate_result.txt
            ai-triage/analysis_result.json
            ai-triage/analysis_result.txt
            repomix-output.txt
          retention-days: 30

